var data = {
    "ubiqumBakeOff": [{
        "bakers": [{
                "name": "Andi",
                "image": "/styles/baker9.png",
                "country": "Albania",
                "flag": "/styles/albania.png",
                "favourite_bakes": "Baklava",
                "course": "Full Stack Web Development",
                "first_challenge_score": "33",
                "second_challenge_score": "34",
                "third_challenge_score": "TBA",
                "fourth_challenge_score": "TBA",
                "info": "Qualified for the third Challenge!",
        },
            {
                "name": "Andras",
                "image": "/styles/baker6.png",
                "country": "Hungary",
                "flag": "/styles/hungary.png",
                "favourite_bakes": "Chocolate Cake",
                "course": "Full Stack 'MERN' Development",
                "first_challenge_score": "19",
                "second_challenge_score": "---",
                "third_challenge_score": "---",
                "fourth_challenge_score": "---",
                "info": "Eliminated on the first Challenge",
                },
            {
                "name": "Anna P.",
                "image": "/styles/baker17.png",
                "country": "Spain",
                "flag": "/styles/spain.png",
                "favourite_bakes": "Palmier",
                "course": "Full Stack Web Development",
                "first_challenge_score": "23",
                "second_challenge_score": "---",
                "third_challenge_score": "---",
                "fourth_challenge_score": "---",
                "info": "Eliminated on the first Challenge",
                },
            {
                "name": "Anna S.",
                "image": "/styles/baker18.png",
                "country": "Greece",
                "flag": "/styles/greece.png",
                "favourite_bakes": "Pavlova",
                "course": "Full Stack 'MERN' Development",
                "first_challenge_score": "25",
                "second_challenge_score": "31",
                "third_challenge_score": "---",
                "fourth_challenge_score": "---",
                "info": "Eliminated on the second Challenge",
                },
            {
                "name": "Claudia",
                "image": "/styles/baker14.png",
                "country": "Portugal",
                "flag": "/styles/portugal.png",
                "favourite_bakes": "Tarte de Pastel de Nata",
                "course": "Full Stack Web Development",
                "first_challenge_score": "37",
                "second_challenge_score": "39",
                "third_challenge_score": "TBA",
                "fourth_challenge_score": "TBA",
                "info": "Qualified for the third Challenge!",
                "email": "claudia@mail.com",
                "password": "claudia",
                },
            {
                "name": "Elvira",
                "image": "/styles/baker15.png",
                "country": "Spain",
                "flag": "/styles/spain.png",
                "favourite_bakes": "Cinnamon Rolls",
                "course": "Full Stack Web Development",
                "first_challenge_score": "34",
                "second_challenge_score": "35",
                "third_challenge_score": "TBA",
                "fourth_challenge_score": "TBA",
                "info": "Qualified for the third Challenge!",
                },     
                   
            {
                "name": "Ernest",
                "image": "/styles/baker4.png",
                "country": "Spain",
                "flag": "/styles/spain.png",
                "favourite_bakes": "Eclair",
                "course": "Full Stack Web Development",
                "first_challenge_score": "35",
                "second_challenge_score": "36",
                "third_challenge_score": "TBA",
                "fourth_challenge_score": "TBA",
                "info": "Qualified for the third Challenge!",
                },
            {
                "name": "Josep",
                "image": "/styles/baker2.png",
                "country": "Spain",
                "flag": "/styles/spain.png",
                "favourite_bakes": "Red Velvet Cake",
                "course": "Full Stack Web Development",
                "first_challenge_score": "28",
                "second_challenge_score": "26",
                "third_challenge_score": "---",
                "fourth_challenge_score": "---",
                "info": "Eliminated on the second Challenge",
                },
            {
                "name": "Lara",
                "image": "/styles/baker16.png",
                "country": "Spain",
                "flag": "/styles/spain.png",
                "favourite_bakes": "Chocolate Pudding",
                "course": "Data Analytics",
                "first_challenge_score": "30",
                "second_challenge_score": "32",
                "third_challenge_score": "TBA",
                "fourth_challenge_score": "TBA",
                "info": "Qualified for the third Challenge!",
                },
            {
                "name": "Ling",
                "image": "/styles/baker3.png",
                "country": "Singapore",
                "flag": "/styles/singapore.png",
                "favourite_bakes": "Apple Pie",
                "course": "Full Stack Web Development",
                "first_challenge_score": "28",
                "second_challenge_score": "29",
                "third_challenge_score": "---",
                "fourth_challenge_score": "---",
                "info": "Eliminated on the second Challenge",
                },
            {
                "name": "Oscar",
                "image": "/styles/baker5.png",
                "country": "Spain",
                "flag": "/styles/spain.png",
                "favourite_bakes": "Rice Pudding",
                "course": "Full Stack Web Development",
                "first_challenge_score": "29",
                "second_challenge_score": "25",
                "third_challenge_score": "---",
                "fourth_challenge_score": "---",
                "info": "Eliminated on the second Challenge",
                },
            {
                "name": "Patrick",
                "image": "/styles/baker12.png",
                "country": "Germany",
                "flag": "/styles/germany.png",
                "favourite_bakes": "Apple Strudel",
                "course": "Full Stack Web Development",
                "first_challenge_score": "20",
                "second_challenge_score": "---",
                "third_challenge_score": "---",
                "fourth_challenge_score": "---",
                "info": "Eliminated on the first Challenge",
                },
            {
                "name": "Santi",
                "image": "/styles/baker1.png",
                "country": "Spain",
                "flag": "/styles/spain.png",
                "favourite_bakes": "Strawberry Cheesecake",
                "course": "Full Stack 'MERN' Development",
                "first_challenge_score": "32",
                "second_challenge_score": "36",
                "third_challenge_score": "TBA",
                "fourth_challenge_score": "TBA",
                "info": "Qualified for the third Challenge!",
                },
            {
                "name": "Uri",
                "image": "/styles/baker10.png",
                "country": "Spain",
                "flag": "/styles/spain.png",
                "favourite_bakes": "Chocolate Cake",
                "course": "Full Stack Web Development",
                "first_challenge_score": "22",
                "second_challenge_score": "---",
                "third_challenge_score": "---",
                "fourth_challenge_score": "---",
                "info": "Eliminated on the first Challenge",
                }


                 ],
        "judges": [{
                "name": "Alex",
                "image": "/styles/baker13.png",
                "country": "Spain",
                "flag": "/styles/spain.png",
                "favourite_desserts": "Mille-feuille",
                "mentor": "Full Stack Mentor",
                },
            {
                "name": "LLuis",
                "image": "/styles/baker11.png",
                "country": "Spain",
                "flag": "/styles/spain.png",
                "favourite_desserts": "Chocolate Chip Cookies",
                "mentor": "Full Stack Mentor",
                },
            {
                "name": "Raul",
                "image": "/styles/baker8.png",
                "country": "Spain",
                "flag": "/styles/spain.png",
                "favourite_desserts": "Brownies",
                "mentor": "Full Stack Mentor",
                },
            {
                "name": "Vasil",
                "image": "/styles/baker7.png",
                "country": "Bulgaria",
                "flag": "/styles/spain.png",
                "favourite_desserts": "Cinnamon Rolls",
                "mentor": "Full Stack Mentor",
                }


            ]

    }]
}
